### ISSUE TITLE
Push 0.5.3 to PyPI

### ISSUE THREAD

**Issue by michael-o** [brandond/requests-negotiate-sspi#29]
PyPI still contains 0.5.2: https://pypi.org/project/requests-negotiate-sspi/. Can someone kindly push 0.5.3 to it?

**Comment by achapkowski** [comment]
@brandond can you please update the 0.5.3 version?  3.9 and 3.10 have been released.

**Comment by michael-o** [comment]
@brandond Gentle reminder.

**Comment by kevinp2** [comment]
Hi folks, can we please update the PyPi version to 0.5.3 ?  Thanks!  I get this error message when using version 0.5.2 with Python 3.10:

```
Traceback (most recent call last):
  File "c:\Users\user.name\Desktop\nprintingapi.py", line 34, in <module>
    from requests_negotiate_sspi import HttpNegotiateAuth
  File "C:\Users\user.name\AppData\Roaming\Python\Python310\site-packages\requests_negotiate_sspi\__init__.py", line 4, in <module>
    from .requests_negotiate_sspi import HttpNegotiateAuth  # noqa
  File "C:\Users\user.name\AppData\Roaming\Python\Python310\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 10, in <module>
    import pywintypes
  File "C:\Program Files\Python3\lib\site-packages\win32\lib\pywintypes.py", line 129, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Program Files\Python3\lib\site-packages\win32\lib\pywintypes.py", line 49, in __import_pywin32_system_module__
    import _win32sysloader
ImportError: Module use of python39.dll conflicts with this version of Python.
```

**Comment by michael-o** [comment]
Waiting :-(

**Comment by michael-o** [comment]
Yet another ping :-(

**Comment by maxglas** [comment]
@brandond 
Will we ever see a newer version on PyPI?

**Comment by michael-o** [comment]
New issues are piling up and still no update :-(
