### ISSUE TITLE
Does not work with Python 3.10 ?

### ISSUE THREAD

**Issue by kevinp2** [brandond/requests-negotiate-sspi#32]
Hi, does this module work with Python 3.10 ?  I get an ImportError on this line:

`from requests_negotiate_sspi import HttpNegotiateAuth
`
**ImportError: Module use of python39.dll conflicts with this version of Python**

```
Traceback (most recent call last):
  File "c:\Users\user.name\Desktop\nprintingapi.py", line 34, in <module>
    from requests_negotiate_sspi import HttpNegotiateAuth
  File "C:\Users\user.name\AppData\Roaming\Python\Python310\site-packages\requests_negotiate_sspi\__init__.py", line 4, in <module>
    from .requests_negotiate_sspi import HttpNegotiateAuth  # noqa
  File "C:\Users\user.name\AppData\Roaming\Python\Python310\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 10, in <module>
    import pywintypes
  File "C:\Program Files\Python3\lib\site-packages\win32\lib\pywintypes.py", line 129, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Program Files\Python3\lib\site-packages\win32\lib\pywintypes.py", line 49, in __import_pywin32_system_module__
    import _win32sysloader
ImportError: Module use of python39.dll conflicts with this version of Python.
```

**Comment by michael-o** [comment]
See: https://github.com/brandond/requests-negotiate-sspi/issues/29
