### ISSUE TITLE
Error during exception handling

### ISSUE THREAD

**Issue by jonashaag** [brandond/requests-negotiate-sspi#40]
```
Traceback (most recent call last):
  File "requests_negotiate_sspi\requests_negotiate_sspi.py", line 121, in _retry_using_http_Negotiate_auth
    error, auth = clientauth.authorize(sec_buffer)
  File "win32\lib\sspi.py", line 232, in authorize
    err, attr, exp = win32security.InitializeSecurityContext(
pywintypes.error: (-2146893044, 'InitializeSecurityContext', 'The logon attempt failed')

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):
  ...
  File "requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "requests\sessions.py", line 708, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
  File "requests\hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "requests_negotiate_sspi\requests_negotiate_sspi.py", line 201, in _response_hook
    return self._retry_using_http_Negotiate_auth(r, scheme, kwargs)
  File "requests_negotiate_sspi\requests_negotiate_sspi.py", line 125, in _retry_using_http_Negotiate_auth
    _logger.debug('Error calling {}: {}'.format(e[1], e[2]), exc_info=e)
TypeError: 'error' object is not subscriptable
```

**Comment by csrujan** [comment]
C:\Users>aws-adfs login --adfs-host=sts.novartis.com --no-ssl-verification
C:\Users\CHALASR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sts.novartis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\CHALASR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sts.novartis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\CHALASR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sts.novartis.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\CHALASR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 181, in _retry_using_http_Negotiate_auth
    error, auth = clientauth.authorize(sec_buffer)
  File "C:\Users\CHALASR1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\win32\lib\sspi.py", line 233, in authorize
    err, attr, exp = win32security.InitializeSecurityContext(
pywintypes.error: (-2146893048, 'InitializeSecurityContext', 'The token supplied to the function is invalid')


can something be done here
