### ISSUE TITLE
pywin32 issue under Python 3.11,6 breaks requests-negotiate-sspi as well

### ISSUE THREAD

**Issue by vhaispdeaded** [brandond/requests-negotiate-sspi#42]
Another issue with latest versions of dependencies. I know this has been solved for previous versions, but it appears a new version of a dependency has reintroduced the issue.

Docker is not an option, it is prohibited on Windows platforms.
Does anyone have a list of versions that will work?

Thank you,

> aws --version
aws-cli/2.14.5 Python/3.11.6 Windows/10 exe/AMD64 prompt/off

```
pip freeze
aws-adfs==2.9.0
boto3==1.33.7
botocore==1.33.7
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
configparser==5.3.0
cryptography==41.0.7
fido2==1.1.2
idna==3.6
jmespath==1.0.1
lxml==4.9.3
pycparser==2.21
pypiwin32==223
python-dateutil==2.8.2
pywin32==306
requests==2.31.0
requests-negotiate-sspi==0.5.2
s3transfer==0.8.2
six==1.16.0
urllib3==2.0.7
```

```
aws-adfs login --adfs-host prod.adfs.federation.<domain redacted> --provider-id urn:amazon:webservices:govcloud --region us-gov-west-1 --role-arn arn:aws-us-gov:iam::**<account redacted>**:role/adfs-project-administrators

C:\Program Files\Python311\Lib\site-packages\urllib3\connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'prod.adfs.federation.va.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 181, in _retry_using_http_Negotiate_auth
    error, auth = clientauth.authorize(sec_buffer)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\win32\lib\sspi.py", line 233, in authorize
    err, attr, exp = win32security.InitializeSecurityContext(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.error: (-2146893048, 'InitializeSecurityContext', 'The token supplied to the function is invalid')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\aws-adfs.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\aws_adfs\login.py", line 218, in login
    principal_roles, assertion, aws_session_duration = authenticator.authenticate(config, assertfile=assertfile)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\aws_adfs\authenticator.py", line 18, in authenticate
    response, session = html_roles_fetcher.fetch_html_encoded_roles(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\aws_adfs\html_roles_fetcher.py", line 103, in fetch_html_encoded_roles
    response = session.post(
               ^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests\sessions.py", line 710, in send
    r = dispatch_hook("response", hooks, r, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests\hooks.py", line 30, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 200, in _response_hook
    return self._retry_using_http_Negotiate_auth(r, scheme, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 185, in _retry_using_http_Negotiate_auth
    _logger.debug('Error calling {}: {}'.format(e[1], e[2]), exc_info=e)
                                                ~^^^
TypeError: 'error' object is not subscriptable
```

**Comment by mavxg** [comment]
Duplicate of issue #40
