### ISSUE TITLE
Does not work with 3.6.1

### ISSUE THREAD

**Issue by ArkBrj** [brandond/requests-negotiate-sspi#7]
Looks like something got broken with Python 3.6.1.
Downgraded back to Python 3.6 (amd64) and verified that my app works fine.
Upgraded to Python 3.6.1 (amd64) again and my app got broken.
I have the most recent packages.

Traceback (most recent call last):
  File "d:\Prj\PyFin\mspc-json.py", line 103, in <module>
    r = s.get(url, headers=hdr)
  File "e:\PyEnv\MS36\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "e:\PyEnv\MS36\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "e:\PyEnv\MS36\lib\site-packages\requests\sessions.py", line 615, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "e:\PyEnv\MS36\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "e:\PyEnv\MS36\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 176, in _response_hook
    return self._retry_using_http_Negotiate_auth(r, scheme, kwargs)
  File "e:\PyEnv\MS36\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 62, in _retry_using_http_Negotiate_auth
    clientauth = sspi.ClientAuth(scheme, targetspn=targetspn, auth_info=self._auth_info)
  File "e:\PyEnv\MS36\lib\site-packages\win32\lib\sspi.py", line 111, in __init__
    None, auth_info)
ValueError: year 30828 is out of range

**Comment by brandond** [comment]
Wow, that's a weird one. Guessing a struct changed somewhere? I'll see if I can repo it on my end. Any details on how you're using it?

**Comment by ArkBrj** [comment]
I am not using anything special actually:

s = requests.Session()
s.auth = HttpNegotiateAuth()
s.verify = False

And then some s.post()/s,get() and bs4 parsing.

**Comment by brandond** [comment]
Looks like this is an issue with Python 3.6.1 being more strict about how Datetimes are created, and Pywin32 passing in a Windows 'never expires' timestamp that was never valid, but used to wrap around due to how the C API handled it... but is now throwing errors due to strict range checks. See https://sourceforge.net/p/pywin32/bugs/748/ and https://bugs.python.org/issue29921

**Comment by ArkBrj** [comment]
Thank you for the investigation.
I am closing this issue since it is not actionable here.
